name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Node.js, NPM and Yarn ‚öôÔ∏è
        uses: actions/setup-node@master
        with:
          node-version: 16
          cache: 'npm'    
      - name: Release Windows
        if: runner.os == 'Windows'
        run: npm run build:win64
      - name: Release MacOS
        if: runner.os == 'macOS'
        run: npm run build:mac  
      - name: Archive production builds üöÄ
        uses: actions/upload-artifact@v2
        with:
          name: dist folder
          path: dist/**
