name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
        uses: actions/checkout@v3
        uses: actions/setup-node@master
        with:
          node-version: 16
          cache: 'npm'
      - name: Build/release Electron app âš’ï¸
        run: npm run rebuild
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
      - name: Archive production builds ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: dist folder
          path: dist/**
