name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install Node.js, NPM and Yarn âš™ï¸
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Build/release Electron app âš’ï¸
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          skip_build: true
          build_script_name: rebuild
      - name: Archive production builds ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: dist folder
          path: dist/**
